bash <(curl -s -L http://asae-build.us.bank-dns.com/detect10.sh) \
--detect.project.name=BSDRate \
--detect.project.version.name=BSDRATE.app.001.01.002 \
--detect.code.location.name=BSDRATE.app.001.01.002 \
--detect.bom.aggregate.name=true \
--detect.project.codelocation.unmap=true \
--blackduck.url=https://usbank.app.blackduck.com \
--blackduck.api.token=M2Y0NzVhZWItNTIyZS00MTI4LWIxODQtYjcxODQ4MmY1YTY4OjNlM2M3OGY4LTc3NzYtNDhhYy05NDdhLTVlY2ZmNGJkMGIwZg== \
--detect.source.path=/D/Development_GIT/GitLab/corptreasury/bsdrate/BSDRate/Application/BSDRate/BSDRateUI \
--blackduck.proxy.host=web-proxymain.us.bank-dns.com \
--blackduck.proxy.port=3128 \
--blackduck.trust.cert=true \
--detect.blackduck.signature.scanner.individual.file.matching=ALL