USE [BSDRate]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/******************************************************************************
Description: Export Daily Curve (MRO) values for SSIS using bullet curve
             definitions across DBC and DB2 export types. Produces columns:
             CURVE, Date, O/N, 7D, 14D, 21D, 1M-360M, Fedtar.

Notes:
- Pulls from ExportRateDefinitions/ExportRateValues joined to
  CalculatedRateDefinitions and LCurrencies.
- Includes both export type codes DBC and DB2 to cover full tenor range.
- Fedtar is included as a column; if no bullet-curve Fed target definition
  exists under DBC/DB2, it will return NULL.

Created by: detolle (based on SSISExportAnnualRatesForMRO)
Modified:   Expanded to include all monthly bullet curves 1M–360M
******************************************************************************/
CREATE OR ALTER PROCEDURE [dbo].[SSISExportDailyCurveMRO]
    @exportDate date = NULL
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @exportTypeCode1 varchar(3) = 'DBC';
    DECLARE @exportTypeCode2 varchar(3) = 'DB2';

    -- SSIS cannot pass NULL; treat 12/30/1899 as NULL sentinel
    IF (ISNULL(@exportDate, '1899-12-30') = '1899-12-30')
    BEGIN
        SET @exportDate = CAST(GETDATE() AS date);
    END

    ;WITH BulletCurve AS (
        SELECT
            CurrencyCode = c.Code,
            erv.RateDate,
            erd.ShortName,
            erv.Value
        FROM ExportRateDefinitions erd
        JOIN LExportTypes et
            ON et.IID = erd.ExportTypeID
           AND et.Code IN (@exportTypeCode1, @exportTypeCode2)
        JOIN CalculatedRateDefinitions crd
            ON crd.CalculatedRateID = erd.BaseRateID
        JOIN LCurrencies c
            ON c.IID = crd.CurrencyID
        JOIN ExportRateValues erv
            ON erv.ExportRateID = erd.ExportRateID
           AND erv.ExportDate = @exportDate
        WHERE erd.ShortName IN (
            '1daybulletcurve',
            '7daybulletcurve',
            '14daybulletcurve',
            '21daybulletcurve',
            '1mobulletcurve',
            '2mobulletcurve',
            '3mobulletcurve',
            '4mobulletcurve',
            '5mobulletcurve',
            '6mobulletcurve',
            '7mobulletcurve',
            '8mobulletcurve',
            '9mobulletcurve',
            '10mobulletcurve',
            '11mobulletcurve',
            '12mobulletcurve',
            '13mobulletcurve',
            '14mobulletcurve',
            '15mobulletcurve',
            '16mobulletcurve',
            '17mobulletcurve',
            '18mobulletcurve',
            '19mobulletcurve',
            '20mobulletcurve',
            '21mobulletcurve',
            '22mobulletcurve',
            '23mobulletcurve',
            '24mobulletcurve',
            '25mobulletcurve',
            '26mobulletcurve',
            '27mobulletcurve',
            '28mobulletcurve',
            '29mobulletcurve',
            '30mobulletcurve',
            '31mobulletcurve',
            '32mobulletcurve',
            '33mobulletcurve',
            '34mobulletcurve',
            '35mobulletcurve',
            '36mobulletcurve',
            '37mobulletcurve',
            '38mobulletcurve',
            '39mobulletcurve',
            '40mobulletcurve',
            '41mobulletcurve',
            '42mobulletcurve',
            '43mobulletcurve',
            '44mobulletcurve',
            '45mobulletcurve',
            '46mobulletcurve',
            '47mobulletcurve',
            '48mobulletcurve',
            '49mobulletcurve',
            '50mobulletcurve',
            '51mobulletcurve',
            '52mobulletcurve',
            '53mobulletcurve',
            '54mobulletcurve',
            '55mobulletcurve',
            '56mobulletcurve',
            '57mobulletcurve',
            '58mobulletcurve',
            '59mobulletcurve',
            '60mobulletcurve',
            '61mobulletcurve',
            '62mobulletcurve',
            '63mobulletcurve',
            '64mobulletcurve',
            '65mobulletcurve',
            '66mobulletcurve',
            '67mobulletcurve',
            '68mobulletcurve',
            '69mobulletcurve',
            '70mobulletcurve',
            '71mobulletcurve',
            '72mobulletcurve',
            '73mobulletcurve',
            '74mobulletcurve',
            '75mobulletcurve',
            '76mobulletcurve',
            '77mobulletcurve',
            '78mobulletcurve',
            '79mobulletcurve',
            '80mobulletcurve',
            '81mobulletcurve',
            '82mobulletcurve',
            '83mobulletcurve',
            '84mobulletcurve',
            '85mobulletcurve',
            '86mobulletcurve',
            '87mobulletcurve',
            '88mobulletcurve',
            '89mobulletcurve',
            '90mobulletcurve',
            '91mobulletcurve',
            '92mobulletcurve',
            '93mobulletcurve',
            '94mobulletcurve',
            '95mobulletcurve',
            '96mobulletcurve',
            '97mobulletcurve',
            '98mobulletcurve',
            '99mobulletcurve',
            '100mobulletcurve',
            '101mobulletcurve',
            '102mobulletcurve',
            '103mobulletcurve',
            '104mobulletcurve',
            '105mobulletcurve',
            '106mobulletcurve',
            '107mobulletcurve',
            '108mobulletcurve',
            '109mobulletcurve',
            '110mobulletcurve',
            '111mobulletcurve',
            '112mobulletcurve',
            '113mobulletcurve',
            '114mobulletcurve',
            '115mobulletcurve',
            '116mobulletcurve',
            '117mobulletcurve',
            '118mobulletcurve',
            '119mobulletcurve',
            '120mobulletcurve',
            '121mobulletcurve',
            '122mobulletcurve',
            '123mobulletcurve',
            '124mobulletcurve',
            '125mobulletcurve',
            '126mobulletcurve',
            '127mobulletcurve',
            '128mobulletcurve',
            '129mobulletcurve',
            '130mobulletcurve',
            '131mobulletcurve',
            '132mobulletcurve',
            '133mobulletcurve',
            '134mobulletcurve',
            '135mobulletcurve',
            '136mobulletcurve',
            '137mobulletcurve',
            '138mobulletcurve',
            '139mobulletcurve',
            '140mobulletcurve',
            '141mobulletcurve',
            '142mobulletcurve',
            '143mobulletcurve',
            '144mobulletcurve',
            '145mobulletcurve',
            '146mobulletcurve',
            '147mobulletcurve',
            '148mobulletcurve',
            '149mobulletcurve',
            '150mobulletcurve',
            '151mobulletcurve',
            '152mobulletcurve',
            '153mobulletcurve',
            '154mobulletcurve',
            '155mobulletcurve',
            '156mobulletcurve',
            '157mobulletcurve',
            '158mobulletcurve',
            '159mobulletcurve',
            '160mobulletcurve',
            '161mobulletcurve',
            '162mobulletcurve',
            '163mobulletcurve',
            '164mobulletcurve',
            '165mobulletcurve',
            '166mobulletcurve',
            '167mobulletcurve',
            '168mobulletcurve',
            '169mobulletcurve',
            '170mobulletcurve',
            '171mobulletcurve',
            '172mobulletcurve',
            '173mobulletcurve',
            '174mobulletcurve',
            '175mobulletcurve',
            '176mobulletcurve',
            '177mobulletcurve',
            '178mobulletcurve',
            '179mobulletcurve',
            '180mobulletcurve',
            '181mobulletcurve',
            '182mobulletcurve',
            '183mobulletcurve',
            '184mobulletcurve',
            '185mobulletcurve',
            '186mobulletcurve',
            '187mobulletcurve',
            '188mobulletcurve',
            '189mobulletcurve',
            '190mobulletcurve',
            '191mobulletcurve',
            '192mobulletcurve',
            '193mobulletcurve',
            '194mobulletcurve',
            '195mobulletcurve',
            '196mobulletcurve',
            '197mobulletcurve',
            '198mobulletcurve',
            '199mobulletcurve',
            '200mobulletcurve',
            '201mobulletcurve',
            '202mobulletcurve',
            '203mobulletcurve',
            '204mobulletcurve',
            '205mobulletcurve',
            '206mobulletcurve',
            '207mobulletcurve',
            '208mobulletcurve',
            '209mobulletcurve',
            '210mobulletcurve',
            '211mobulletcurve',
            '212mobulletcurve',
            '213mobulletcurve',
            '214mobulletcurve',
            '215mobulletcurve',
            '216mobulletcurve',
            '217mobulletcurve',
            '218mobulletcurve',
            '219mobulletcurve',
            '220mobulletcurve',
            '221mobulletcurve',
            '222mobulletcurve',
            '223mobulletcurve',
            '224mobulletcurve',
            '225mobulletcurve',
            '226mobulletcurve',
            '227mobulletcurve',
            '228mobulletcurve',
            '229mobulletcurve',
            '230mobulletcurve',
            '231mobulletcurve',
            '232mobulletcurve',
            '233mobulletcurve',
            '234mobulletcurve',
            '235mobulletcurve',
            '236mobulletcurve',
            '237mobulletcurve',
            '238mobulletcurve',
            '239mobulletcurve',
            '240mobulletcurve',
            '241mobulletcurve',
            '242mobulletcurve',
            '243mobulletcurve',
            '244mobulletcurve',
            '245mobulletcurve',
            '246mobulletcurve',
            '247mobulletcurve',
            '248mobulletcurve',
            '249mobulletcurve',
            '250mobulletcurve',
            '251mobulletcurve',
            '252mobulletcurve',
            '253mobulletcurve',
            '254mobulletcurve',
            '255mobulletcurve',
            '256mobulletcurve',
            '257mobulletcurve',
            '258mobulletcurve',
            '259mobulletcurve',
            '260mobulletcurve',
            '261mobulletcurve',
            '262mobulletcurve',
            '263mobulletcurve',
            '264mobulletcurve',
            '265mobulletcurve',
            '266mobulletcurve',
            '267mobulletcurve',
            '268mobulletcurve',
            '269mobulletcurve',
            '270mobulletcurve',
            '271mobulletcurve',
            '272mobulletcurve',
            '273mobulletcurve',
            '274mobulletcurve',
            '275mobulletcurve',
            '276mobulletcurve',
            '277mobulletcurve',
            '278mobulletcurve',
            '279mobulletcurve',
            '280mobulletcurve',
            '281mobulletcurve',
            '282mobulletcurve',
            '283mobulletcurve',
            '284mobulletcurve',
            '285mobulletcurve',
            '286mobulletcurve',
            '287mobulletcurve',
            '288mobulletcurve',
            '289mobulletcurve',
            '290mobulletcurve',
            '291mobulletcurve',
            '292mobulletcurve',
            '293mobulletcurve',
            '294mobulletcurve',
            '295mobulletcurve',
            '296mobulletcurve',
            '297mobulletcurve',
            '298mobulletcurve',
            '299mobulletcurve',
            '300mobulletcurve',
            '301mobulletcurve',
            '302mobulletcurve',
            '303mobulletcurve',
            '304mobulletcurve',
            '305mobulletcurve',
            '306mobulletcurve',
            '307mobulletcurve',
            '308mobulletcurve',
            '309mobulletcurve',
            '310mobulletcurve',
            '311mobulletcurve',
            '312mobulletcurve',
            '313mobulletcurve',
            '314mobulletcurve',
            '315mobulletcurve',
            '316mobulletcurve',
            '317mobulletcurve',
            '318mobulletcurve',
            '319mobulletcurve',
            '320mobulletcurve',
            '321mobulletcurve',
            '322mobulletcurve',
            '323mobulletcurve',
            '324mobulletcurve',
            '325mobulletcurve',
            '326mobulletcurve',
            '327mobulletcurve',
            '328mobulletcurve',
            '329mobulletcurve',
            '330mobulletcurve',
            '331mobulletcurve',
            '332mobulletcurve',
            '333mobulletcurve',
            '334mobulletcurve',
            '335mobulletcurve',
            '336mobulletcurve',
            '337mobulletcurve',
            '338mobulletcurve',
            '339mobulletcurve',
            '340mobulletcurve',
            '341mobulletcurve',
            '342mobulletcurve',
            '343mobulletcurve',
            '344mobulletcurve',
            '345mobulletcurve',
            '346mobulletcurve',
            '347mobulletcurve',
            '348mobulletcurve',
            '349mobulletcurve',
            '350mobulletcurve',
            '351mobulletcurve',
            '352mobulletcurve',
            '353mobulletcurve',
            '354mobulletcurve',
            '355mobulletcurve',
            '356mobulletcurve',
            '357mobulletcurve',
            '358mobulletcurve',
            '359mobulletcurve',
            '360mobulletcurve',
            'fedtarzca'

        )
    ),
    Pivoted AS (
        SELECT
            CurrencyCode,
            RateDate,
            1daybulletcurve,
            7daybulletcurve,
            14daybulletcurve,
            21daybulletcurve,
            [1mobulletcurve],
            [2mobulletcurve],
            [3mobulletcurve],
            [4mobulletcurve],
            [5mobulletcurve],
            [6mobulletcurve],
            [7mobulletcurve],
            [8mobulletcurve],
            [9mobulletcurve],
            [10mobulletcurve],
            [11mobulletcurve],
            [12mobulletcurve],
            [13mobulletcurve],
            [14mobulletcurve],
            [15mobulletcurve],
            [16mobulletcurve],
            [17mobulletcurve],
            [18mobulletcurve],
            [19mobulletcurve],
            [20mobulletcurve],
            [21mobulletcurve],
            [22mobulletcurve],
            [23mobulletcurve],
            [24mobulletcurve],
            [25mobulletcurve],
            [26mobulletcurve],
            [27mobulletcurve],
            [28mobulletcurve],
            [29mobulletcurve],
            [30mobulletcurve],
            [31mobulletcurve],
            [32mobulletcurve],
            [33mobulletcurve],
            [34mobulletcurve],
            [35mobulletcurve],
            [36mobulletcurve],
            [37mobulletcurve],
            [38mobulletcurve],
            [39mobulletcurve],
            [40mobulletcurve],
            [41mobulletcurve],
            [42mobulletcurve],
            [43mobulletcurve],
            [44mobulletcurve],
            [45mobulletcurve],
            [46mobulletcurve],
            [47mobulletcurve],
            [48mobulletcurve],
            [49mobulletcurve],
            [50mobulletcurve],
            [51mobulletcurve],
            [52mobulletcurve],
            [53mobulletcurve],
            [54mobulletcurve],
            [55mobulletcurve],
            [56mobulletcurve],
            [57mobulletcurve],
            [58mobulletcurve],
            [59mobulletcurve],
            [60mobulletcurve],
            [61mobulletcurve],
            [62mobulletcurve],
            [63mobulletcurve],
            [64mobulletcurve],
            [65mobulletcurve],
            [66mobulletcurve],
            [67mobulletcurve],
            [68mobulletcurve],
            [69mobulletcurve],
            [70mobulletcurve],
            [71mobulletcurve],
            [72mobulletcurve],
            [73mobulletcurve],
            [74mobulletcurve],
            [75mobulletcurve],
            [76mobulletcurve],
            [77mobulletcurve],
            [78mobulletcurve],
            [79mobulletcurve],
            [80mobulletcurve],
            [81mobulletcurve],
            [82mobulletcurve],
            [83mobulletcurve],
            [84mobulletcurve],
            [85mobulletcurve],
            [86mobulletcurve],
            [87mobulletcurve],
            [88mobulletcurve],
            [89mobulletcurve],
            [90mobulletcurve],
            [91mobulletcurve],
            [92mobulletcurve],
            [93mobulletcurve],
            [94mobulletcurve],
            [95mobulletcurve],
            [96mobulletcurve],
            [97mobulletcurve],
            [98mobulletcurve],
            [99mobulletcurve],
            [100mobulletcurve],
            [101mobulletcurve],
            [102mobulletcurve],
            [103mobulletcurve],
            [104mobulletcurve],
            [105mobulletcurve],
            [106mobulletcurve],
            [107mobulletcurve],
            [108mobulletcurve],
            [109mobulletcurve],
            [110mobulletcurve],
            [111mobulletcurve],
            [112mobulletcurve],
            [113mobulletcurve],
            [114mobulletcurve],
            [115mobulletcurve],
            [116mobulletcurve],
            [117mobulletcurve],
            [118mobulletcurve],
            [119mobulletcurve],
            [120mobulletcurve],
            [121mobulletcurve],
            [122mobulletcurve],
            [123mobulletcurve],
            [124mobulletcurve],
            [125mobulletcurve],
            [126mobulletcurve],
            [127mobulletcurve],
            [128mobulletcurve],
            [129mobulletcurve],
            [130mobulletcurve],
            [131mobulletcurve],
            [132mobulletcurve],
            [133mobulletcurve],
            [134mobulletcurve],
            [135mobulletcurve],
            [136mobulletcurve],
            [137mobulletcurve],
            [138mobulletcurve],
            [139mobulletcurve],
            [140mobulletcurve],
            [141mobulletcurve],
            [142mobulletcurve],
            [143mobulletcurve],
            [144mobulletcurve],
            [145mobulletcurve],
            [146mobulletcurve],
            [147mobulletcurve],
            [148mobulletcurve],
            [149mobulletcurve],
            [150mobulletcurve],
            [151mobulletcurve],
            [152mobulletcurve],
            [153mobulletcurve],
            [154mobulletcurve],
            [155mobulletcurve],
            [156mobulletcurve],
            [157mobulletcurve],
            [158mobulletcurve],
            [159mobulletcurve],
            [160mobulletcurve],
            [161mobulletcurve],
            [162mobulletcurve],
            [163mobulletcurve],
            [164mobulletcurve],
            [165mobulletcurve],
            [166mobulletcurve],
            [167mobulletcurve],
            [168mobulletcurve],
            [169mobulletcurve],
            [170mobulletcurve],
            [171mobulletcurve],
            [172mobulletcurve],
            [173mobulletcurve],
            [174mobulletcurve],
            [175mobulletcurve],
            [176mobulletcurve],
            [177mobulletcurve],
            [178mobulletcurve],
            [179mobulletcurve],
            [180mobulletcurve],
            [181mobulletcurve],
            [182mobulletcurve],
            [183mobulletcurve],
            [184mobulletcurve],
            [185mobulletcurve],
            [186mobulletcurve],
            [187mobulletcurve],
            [188mobulletcurve],
            [189mobulletcurve],
            [190mobulletcurve],
            [191mobulletcurve],
            [192mobulletcurve],
            [193mobulletcurve],
            [194mobulletcurve],
            [195mobulletcurve],
            [196mobulletcurve],
            [197mobulletcurve],
            [198mobulletcurve],
            [199mobulletcurve],
            [200mobulletcurve],
            [201mobulletcurve],
            [202mobulletcurve],
            [203mobulletcurve],
            [204mobulletcurve],
            [205mobulletcurve],
            [206mobulletcurve],
            [207mobulletcurve],
            [208mobulletcurve],
            [209mobulletcurve],
            [210mobulletcurve],
            [211mobulletcurve],
            [212mobulletcurve],
            [213mobulletcurve],
            [214mobulletcurve],
            [215mobulletcurve],
            [216mobulletcurve],
            [217mobulletcurve],
            [218mobulletcurve],
            [219mobulletcurve],
            [220mobulletcurve],
            [221mobulletcurve],
            [222mobulletcurve],
            [223mobulletcurve],
            [224mobulletcurve],
            [225mobulletcurve],
            [226mobulletcurve],
            [227mobulletcurve],
            [228mobulletcurve],
            [229mobulletcurve],
            [230mobulletcurve],
            [231mobulletcurve],
            [232mobulletcurve],
            [233mobulletcurve],
            [234mobulletcurve],
            [235mobulletcurve],
            [236mobulletcurve],
            [237mobulletcurve],
            [238mobulletcurve],
            [239mobulletcurve],
            [240mobulletcurve],
            [241mobulletcurve],
            [242mobulletcurve],
            [243mobulletcurve],
            [244mobulletcurve],
            [245mobulletcurve],
            [246mobulletcurve],
            [247mobulletcurve],
            [248mobulletcurve],
            [249mobulletcurve],
            [250mobulletcurve],
            [251mobulletcurve],
            [252mobulletcurve],
            [253mobulletcurve],
            [254mobulletcurve],
            [255mobulletcurve],
            [256mobulletcurve],
            [257mobulletcurve],
            [258mobulletcurve],
            [259mobulletcurve],
            [260mobulletcurve],
            [261mobulletcurve],
            [262mobulletcurve],
            [263mobulletcurve],
            [264mobulletcurve],
            [265mobulletcurve],
            [266mobulletcurve],
            [267mobulletcurve],
            [268mobulletcurve],
            [269mobulletcurve],
            [270mobulletcurve],
            [271mobulletcurve],
            [272mobulletcurve],
            [273mobulletcurve],
            [274mobulletcurve],
            [275mobulletcurve],
            [276mobulletcurve],
            [277mobulletcurve],
            [278mobulletcurve],
            [279mobulletcurve],
            [280mobulletcurve],
            [281mobulletcurve],
            [282mobulletcurve],
            [283mobulletcurve],
            [284mobulletcurve],
            [285mobulletcurve],
            [286mobulletcurve],
            [287mobulletcurve],
            [288mobulletcurve],
            [289mobulletcurve],
            [290mobulletcurve],
            [291mobulletcurve],
            [292mobulletcurve],
            [293mobulletcurve],
            [294mobulletcurve],
            [295mobulletcurve],
            [296mobulletcurve],
            [297mobulletcurve],
            [298mobulletcurve],
            [299mobulletcurve],
            [300mobulletcurve],
            [301mobulletcurve],
            [302mobulletcurve],
            [303mobulletcurve],
            [304mobulletcurve],
            [305mobulletcurve],
            [306mobulletcurve],
            [307mobulletcurve],
            [308mobulletcurve],
            [309mobulletcurve],
            [310mobulletcurve],
            [311mobulletcurve],
            [312mobulletcurve],
            [313mobulletcurve],
            [314mobulletcurve],
            [315mobulletcurve],
            [316mobulletcurve],
            [317mobulletcurve],
            [318mobulletcurve],
            [319mobulletcurve],
            [320mobulletcurve],
            [321mobulletcurve],
            [322mobulletcurve],
            [323mobulletcurve],
            [324mobulletcurve],
            [325mobulletcurve],
            [326mobulletcurve],
            [327mobulletcurve],
            [328mobulletcurve],
            [329mobulletcurve],
            [330mobulletcurve],
            [331mobulletcurve],
            [332mobulletcurve],
            [333mobulletcurve],
            [334mobulletcurve],
            [335mobulletcurve],
            [336mobulletcurve],
            [337mobulletcurve],
            [338mobulletcurve],
            [339mobulletcurve],
            [340mobulletcurve],
            [341mobulletcurve],
            [342mobulletcurve],
            [343mobulletcurve],
            [344mobulletcurve],
            [345mobulletcurve],
            [346mobulletcurve],
            [347mobulletcurve],
            [348mobulletcurve],
            [349mobulletcurve],
            [350mobulletcurve],
            [351mobulletcurve],
            [352mobulletcurve],
            [353mobulletcurve],
            [354mobulletcurve],
            [355mobulletcurve],
            [356mobulletcurve],
            [357mobulletcurve],
            [358mobulletcurve],
            [359mobulletcurve],
            [360mobulletcurve]
        FROM BulletCurve AS src
        PIVOT (
            MAX(Value) FOR ShortName IN (
                1daybulletcurve,
                7daybulletcurve,
                14daybulletcurve,
                21daybulletcurve,
                [1mobulletcurve],
                [2mobulletcurve],
                [3mobulletcurve],
                [4mobulletcurve],
                [5mobulletcurve],
                [6mobulletcurve],
                [7mobulletcurve],
                [8mobulletcurve],
                [9mobulletcurve],
                [10mobulletcurve],
                [11mobulletcurve],
                [12mobulletcurve],
                [13mobulletcurve],
                [14mobulletcurve],
                [15mobulletcurve],
                [16mobulletcurve],
                [17mobulletcurve],
                [18mobulletcurve],
                [19mobulletcurve],
                [20mobulletcurve],
                [21mobulletcurve],
                [22mobulletcurve],
                [23mobulletcurve],
                [24mobulletcurve],
                [25mobulletcurve],
                [26mobulletcurve],
                [27mobulletcurve],
                [28mobulletcurve],
                [29mobulletcurve],
                [30mobulletcurve],
                [31mobulletcurve],
                [32mobulletcurve],
                [33mobulletcurve],
                [34mobulletcurve],
                [35mobulletcurve],
                [36mobulletcurve],
                [37mobulletcurve],
                [38mobulletcurve],
                [39mobulletcurve],
                [40mobulletcurve],
                [41mobulletcurve],
                [42mobulletcurve],
                [43mobulletcurve],
                [44mobulletcurve],
                [45mobulletcurve],
                [46mobulletcurve],
                [47mobulletcurve],
                [48mobulletcurve],
                [49mobulletcurve],
                [50mobulletcurve],
                [51mobulletcurve],
                [52mobulletcurve],
                [53mobulletcurve],
                [54mobulletcurve],
                [55mobulletcurve],
                [56mobulletcurve],
                [57mobulletcurve],
                [58mobulletcurve],
                [59mobulletcurve],
                [60mobulletcurve],
                [61mobulletcurve],
                [62mobulletcurve],
                [63mobulletcurve],
                [64mobulletcurve],
                [65mobulletcurve],
                [66mobulletcurve],
                [67mobulletcurve],
                [68mobulletcurve],
                [69mobulletcurve],
                [70mobulletcurve],
                [71mobulletcurve],
                [72mobulletcurve],
                [73mobulletcurve],
                [74mobulletcurve],
                [75mobulletcurve],
                [76mobulletcurve],
                [77mobulletcurve],
                [78mobulletcurve],
                [79mobulletcurve],
                [80mobulletcurve],
                [81mobulletcurve],
                [82mobulletcurve],
                [83mobulletcurve],
                [84mobulletcurve],
                [85mobulletcurve],
                [86mobulletcurve],
                [87mobulletcurve],
                [88mobulletcurve],
                [89mobulletcurve],
                [90mobulletcurve],
                [91mobulletcurve],
                [92mobulletcurve],
                [93mobulletcurve],
                [94mobulletcurve],
                [95mobulletcurve],
                [96mobulletcurve],
                [97mobulletcurve],
                [98mobulletcurve],
                [99mobulletcurve],
                [100mobulletcurve],
                [101mobulletcurve],
                [102mobulletcurve],
                [103mobulletcurve],
                [104mobulletcurve],
                [105mobulletcurve],
                [106mobulletcurve],
                [107mobulletcurve],
                [108mobulletcurve],
                [109mobulletcurve],
                [110mobulletcurve],
                [111mobulletcurve],
                [112mobulletcurve],
                [113mobulletcurve],
                [114mobulletcurve],
                [115mobulletcurve],
                [116mobulletcurve],
                [117mobulletcurve],
                [118mobulletcurve],
                [119mobulletcurve],
                [120mobulletcurve],
                [121mobulletcurve],
                [122mobulletcurve],
                [123mobulletcurve],
                [124mobulletcurve],
                [125mobulletcurve],
                [126mobulletcurve],
                [127mobulletcurve],
                [128mobulletcurve],
                [129mobulletcurve],
                [130mobulletcurve],
                [131mobulletcurve],
                [132mobulletcurve],
                [133mobulletcurve],
                [134mobulletcurve],
                [135mobulletcurve],
                [136mobulletcurve],
                [137mobulletcurve],
                [138mobulletcurve],
                [139mobulletcurve],
                [140mobulletcurve],
                [141mobulletcurve],
                [142mobulletcurve],
                [143mobulletcurve],
                [144mobulletcurve],
                [145mobulletcurve],
                [146mobulletcurve],
                [147mobulletcurve],
                [148mobulletcurve],
                [149mobulletcurve],
                [150mobulletcurve],
                [151mobulletcurve],
                [152mobulletcurve],
                [153mobulletcurve],
                [154mobulletcurve],
                [155mobulletcurve],
                [156mobulletcurve],
                [157mobulletcurve],
                [158mobulletcurve],
                [159mobulletcurve],
                [160mobulletcurve],
                [161mobulletcurve],
                [162mobulletcurve],
                [163mobulletcurve],
                [164mobulletcurve],
                [165mobulletcurve],
                [166mobulletcurve],
                [167mobulletcurve],
                [168mobulletcurve],
                [169mobulletcurve],
                [170mobulletcurve],
                [171mobulletcurve],
                [172mobulletcurve],
                [173mobulletcurve],
                [174mobulletcurve],
                [175mobulletcurve],
                [176mobulletcurve],
                [177mobulletcurve],
                [178mobulletcurve],
                [179mobulletcurve],
                [180mobulletcurve],
                [181mobulletcurve],
                [182mobulletcurve],
                [183mobulletcurve],
                [184mobulletcurve],
                [185mobulletcurve],
                [186mobulletcurve],
                [187mobulletcurve],
                [188mobulletcurve],
                [189mobulletcurve],
                [190mobulletcurve],
                [191mobulletcurve],
                [192mobulletcurve],
                [193mobulletcurve],
                [194mobulletcurve],
                [195mobulletcurve],
                [196mobulletcurve],
                [197mobulletcurve],
                [198mobulletcurve],
                [199mobulletcurve],
                [200mobulletcurve],
                [201mobulletcurve],
                [202mobulletcurve],
                [203mobulletcurve],
                [204mobulletcurve],
                [205mobulletcurve],
                [206mobulletcurve],
                [207mobulletcurve],
                [208mobulletcurve],
                [209mobulletcurve],
                [210mobulletcurve],
                [211mobulletcurve],
                [212mobulletcurve],
                [213mobulletcurve],
                [214mobulletcurve],
                [215mobulletcurve],
                [216mobulletcurve],
                [217mobulletcurve],
                [218mobulletcurve],
                [219mobulletcurve],
                [220mobulletcurve],
                [221mobulletcurve],
                [222mobulletcurve],
                [223mobulletcurve],
                [224mobulletcurve],
                [225mobulletcurve],
                [226mobulletcurve],
                [227mobulletcurve],
                [228mobulletcurve],
                [229mobulletcurve],
                [230mobulletcurve],
                [231mobulletcurve],
                [232mobulletcurve],
                [233mobulletcurve],
                [234mobulletcurve],
                [235mobulletcurve],
                [236mobulletcurve],
                [237mobulletcurve],
                [238mobulletcurve],
                [239mobulletcurve],
                [240mobulletcurve],
                [241mobulletcurve],
                [242mobulletcurve],
                [243mobulletcurve],
                [244mobulletcurve],
                [245mobulletcurve],
                [246mobulletcurve],
                [247mobulletcurve],
                [248mobulletcurve],
                [249mobulletcurve],
                [250mobulletcurve],
                [251mobulletcurve],
                [252mobulletcurve],
                [253mobulletcurve],
                [254mobulletcurve],
                [255mobulletcurve],
                [256mobulletcurve],
                [257mobulletcurve],
                [258mobulletcurve],
                [259mobulletcurve],
                [260mobulletcurve],
                [261mobulletcurve],
                [262mobulletcurve],
                [263mobulletcurve],
                [264mobulletcurve],
                [265mobulletcurve],
                [266mobulletcurve],
                [267mobulletcurve],
                [268mobulletcurve],
                [269mobulletcurve],
                [270mobulletcurve],
                [271mobulletcurve],
                [272mobulletcurve],
                [273mobulletcurve],
                [274mobulletcurve],
                [275mobulletcurve],
                [276mobulletcurve],
                [277mobulletcurve],
                [278mobulletcurve],
                [279mobulletcurve],
                [280mobulletcurve],
                [281mobulletcurve],
                [282mobulletcurve],
                [283mobulletcurve],
                [284mobulletcurve],
                [285mobulletcurve],
                [286mobulletcurve],
                [287mobulletcurve],
                [288mobulletcurve],
                [289mobulletcurve],
                [290mobulletcurve],
                [291mobulletcurve],
                [292mobulletcurve],
                [293mobulletcurve],
                [294mobulletcurve],
                [295mobulletcurve],
                [296mobulletcurve],
                [297mobulletcurve],
                [298mobulletcurve],
                [299mobulletcurve],
                [300mobulletcurve],
                [301mobulletcurve],
                [302mobulletcurve],
                [303mobulletcurve],
                [304mobulletcurve],
                [305mobulletcurve],
                [306mobulletcurve],
                [307mobulletcurve],
                [308mobulletcurve],
                [309mobulletcurve],
                [310mobulletcurve],
                [311mobulletcurve],
                [312mobulletcurve],
                [313mobulletcurve],
                [314mobulletcurve],
                [315mobulletcurve],
                [316mobulletcurve],
                [317mobulletcurve],
                [318mobulletcurve],
                [319mobulletcurve],
                [320mobulletcurve],
                [321mobulletcurve],
                [322mobulletcurve],
                [323mobulletcurve],
                [324mobulletcurve],
                [325mobulletcurve],
                [326mobulletcurve],
                [327mobulletcurve],
                [328mobulletcurve],
                [329mobulletcurve],
                [330mobulletcurve],
                [331mobulletcurve],
                [332mobulletcurve],
                [333mobulletcurve],
                [334mobulletcurve],
                [335mobulletcurve],
                [336mobulletcurve],
                [337mobulletcurve],
                [338mobulletcurve],
                [339mobulletcurve],
                [340mobulletcurve],
                [341mobulletcurve],
                [342mobulletcurve],
                [343mobulletcurve],
                [344mobulletcurve],
                [345mobulletcurve],
                [346mobulletcurve],
                [347mobulletcurve],
                [348mobulletcurve],
                [349mobulletcurve],
                [350mobulletcurve],
                [351mobulletcurve],
                [352mobulletcurve],
                [353mobulletcurve],
                [354mobulletcurve],
                [355mobulletcurve],
                [356mobulletcurve],
                [357mobulletcurve],
                [358mobulletcurve],
                [359mobulletcurve],
                [360mobulletcurve],
                [fedtarzca]
            )
        ) AS p
    )
    SELECT
        [CURVE]  = CurrencyCode,
        [Date]   = CONVERT(varchar, RateDate, 101),
        [O/N]    = CAST(([1daybulletcurve] * 100) AS varchar),
        [7D]     = CAST(([7daybulletcurve] * 100) AS varchar),
        [14D]    = CAST(([14daybulletcurve] * 100) AS varchar),
        [21D]    = CAST(([21daybulletcurve] * 100) AS varchar),
        [1M]    = CAST(([1mobulletcurve] * 100) AS varchar),
        [2M]    = CAST(([2mobulletcurve] * 100) AS varchar),
        [3M]    = CAST(([3mobulletcurve] * 100) AS varchar),
        [4M]    = CAST(([4mobulletcurve] * 100) AS varchar),
        [5M]    = CAST(([5mobulletcurve] * 100) AS varchar),
        [6M]    = CAST(([6mobulletcurve] * 100) AS varchar),
        [7M]    = CAST(([7mobulletcurve] * 100) AS varchar),
        [8M]    = CAST(([8mobulletcurve] * 100) AS varchar),
        [9M]    = CAST(([9mobulletcurve] * 100) AS varchar),
        [10M]    = CAST(([10mobulletcurve] * 100) AS varchar),
        [11M]    = CAST(([11mobulletcurve] * 100) AS varchar),
        [12M]    = CAST(([12mobulletcurve] * 100) AS varchar),
        [13M]    = CAST(([13mobulletcurve] * 100) AS varchar),
        [14M]    = CAST(([14mobulletcurve] * 100) AS varchar),
        [15M]    = CAST(([15mobulletcurve] * 100) AS varchar),
        [16M]    = CAST(([16mobulletcurve] * 100) AS varchar),
        [17M]    = CAST(([17mobulletcurve] * 100) AS varchar),
        [18M]    = CAST(([18mobulletcurve] * 100) AS varchar),
        [19M]    = CAST(([19mobulletcurve] * 100) AS varchar),
        [20M]    = CAST(([20mobulletcurve] * 100) AS varchar),
        [21M]    = CAST(([21mobulletcurve] * 100) AS varchar),
        [22M]    = CAST(([22mobulletcurve] * 100) AS varchar),
        [23M]    = CAST(([23mobulletcurve] * 100) AS varchar),
        [24M]    = CAST(([24mobulletcurve] * 100) AS varchar),
        [25M]    = CAST(([25mobulletcurve] * 100) AS varchar),
        [26M]    = CAST(([26mobulletcurve] * 100) AS varchar),
        [27M]    = CAST(([27mobulletcurve] * 100) AS varchar),
        [28M]    = CAST(([28mobulletcurve] * 100) AS varchar),
        [29M]    = CAST(([29mobulletcurve] * 100) AS varchar),
        [30M]    = CAST(([30mobulletcurve] * 100) AS varchar),
        [31M]    = CAST(([31mobulletcurve] * 100) AS varchar),
        [32M]    = CAST(([32mobulletcurve] * 100) AS varchar),
        [33M]    = CAST(([33mobulletcurve] * 100) AS varchar),
        [34M]    = CAST(([34mobulletcurve] * 100) AS varchar),
        [35M]    = CAST(([35mobulletcurve] * 100) AS varchar),
        [36M]    = CAST(([36mobulletcurve] * 100) AS varchar),
        [37M]    = CAST(([37mobulletcurve] * 100) AS varchar),
        [38M]    = CAST(([38mobulletcurve] * 100) AS varchar),
        [39M]    = CAST(([39mobulletcurve] * 100) AS varchar),
        [40M]    = CAST(([40mobulletcurve] * 100) AS varchar),
        [41M]    = CAST(([41mobulletcurve] * 100) AS varchar),
        [42M]    = CAST(([42mobulletcurve] * 100) AS varchar),
        [43M]    = CAST(([43mobulletcurve] * 100) AS varchar),
        [44M]    = CAST(([44mobulletcurve] * 100) AS varchar),
        [45M]    = CAST(([45mobulletcurve] * 100) AS varchar),
        [46M]    = CAST(([46mobulletcurve] * 100) AS varchar),
        [47M]    = CAST(([47mobulletcurve] * 100) AS varchar),
        [48M]    = CAST(([48mobulletcurve] * 100) AS varchar),
        [49M]    = CAST(([49mobulletcurve] * 100) AS varchar),
        [50M]    = CAST(([50mobulletcurve] * 100) AS varchar),
        [51M]    = CAST(([51mobulletcurve] * 100) AS varchar),
        [52M]    = CAST(([52mobulletcurve] * 100) AS varchar),
        [53M]    = CAST(([53mobulletcurve] * 100) AS varchar),
        [54M]    = CAST(([54mobulletcurve] * 100) AS varchar),
        [55M]    = CAST(([55mobulletcurve] * 100) AS varchar),
        [56M]    = CAST(([56mobulletcurve] * 100) AS varchar),
        [57M]    = CAST(([57mobulletcurve] * 100) AS varchar),
        [58M]    = CAST(([58mobulletcurve] * 100) AS varchar),
        [59M]    = CAST(([59mobulletcurve] * 100) AS varchar),
        [60M]    = CAST(([60mobulletcurve] * 100) AS varchar),
        [61M]    = CAST(([61mobulletcurve] * 100) AS varchar),
        [62M]    = CAST(([62mobulletcurve] * 100) AS varchar),
        [63M]    = CAST(([63mobulletcurve] * 100) AS varchar),
        [64M]    = CAST(([64mobulletcurve] * 100) AS varchar),
        [65M]    = CAST(([65mobulletcurve] * 100) AS varchar),
        [66M]    = CAST(([66mobulletcurve] * 100) AS varchar),
        [67M]    = CAST(([67mobulletcurve] * 100) AS varchar),
        [68M]    = CAST(([68mobulletcurve] * 100) AS varchar),
        [69M]    = CAST(([69mobulletcurve] * 100) AS varchar),
        [70M]    = CAST(([70mobulletcurve] * 100) AS varchar),
        [71M]    = CAST(([71mobulletcurve] * 100) AS varchar),
        [72M]    = CAST(([72mobulletcurve] * 100) AS varchar),
        [73M]    = CAST(([73mobulletcurve] * 100) AS varchar),
        [74M]    = CAST(([74mobulletcurve] * 100) AS varchar),
        [75M]    = CAST(([75mobulletcurve] * 100) AS varchar),
        [76M]    = CAST(([76mobulletcurve] * 100) AS varchar),
        [77M]    = CAST(([77mobulletcurve] * 100) AS varchar),
        [78M]    = CAST(([78mobulletcurve] * 100) AS varchar),
        [79M]    = CAST(([79mobulletcurve] * 100) AS varchar),
        [80M]    = CAST(([80mobulletcurve] * 100) AS varchar),
        [81M]    = CAST(([81mobulletcurve] * 100) AS varchar),
        [82M]    = CAST(([82mobulletcurve] * 100) AS varchar),
        [83M]    = CAST(([83mobulletcurve] * 100) AS varchar),
        [84M]    = CAST(([84mobulletcurve] * 100) AS varchar),
        [85M]    = CAST(([85mobulletcurve] * 100) AS varchar),
        [86M]    = CAST(([86mobulletcurve] * 100) AS varchar),
        [87M]    = CAST(([87mobulletcurve] * 100) AS varchar),
        [88M]    = CAST(([88mobulletcurve] * 100) AS varchar),
        [89M]    = CAST(([89mobulletcurve] * 100) AS varchar),
        [90M]    = CAST(([90mobulletcurve] * 100) AS varchar),
        [91M]    = CAST(([91mobulletcurve] * 100) AS varchar),
        [92M]    = CAST(([92mobulletcurve] * 100) AS varchar),
        [93M]    = CAST(([93mobulletcurve] * 100) AS varchar),
        [94M]    = CAST(([94mobulletcurve] * 100) AS varchar),
        [95M]    = CAST(([95mobulletcurve] * 100) AS varchar),
        [96M]    = CAST(([96mobulletcurve] * 100) AS varchar),
        [97M]    = CAST(([97mobulletcurve] * 100) AS varchar),
        [98M]    = CAST(([98mobulletcurve] * 100) AS varchar),
        [99M]    = CAST(([99mobulletcurve] * 100) AS varchar),
        [100M]    = CAST(([100mobulletcurve] * 100) AS varchar),
        [101M]    = CAST(([101mobulletcurve] * 100) AS varchar),
        [102M]    = CAST(([102mobulletcurve] * 100) AS varchar),
        [103M]    = CAST(([103mobulletcurve] * 100) AS varchar),
        [104M]    = CAST(([104mobulletcurve] * 100) AS varchar),
        [105M]    = CAST(([105mobulletcurve] * 100) AS varchar),
        [106M]    = CAST(([106mobulletcurve] * 100) AS varchar),
        [107M]    = CAST(([107mobulletcurve] * 100) AS varchar),
        [108M]    = CAST(([108mobulletcurve] * 100) AS varchar),
        [109M]    = CAST(([109mobulletcurve] * 100) AS varchar),
        [110M]    = CAST(([110mobulletcurve] * 100) AS varchar),
        [111M]    = CAST(([111mobulletcurve] * 100) AS varchar),
        [112M]    = CAST(([112mobulletcurve] * 100) AS varchar),
        [113M]    = CAST(([113mobulletcurve] * 100) AS varchar),
        [114M]    = CAST(([114mobulletcurve] * 100) AS varchar),
        [115M]    = CAST(([115mobulletcurve] * 100) AS varchar),
        [116M]    = CAST(([116mobulletcurve] * 100) AS varchar),
        [117M]    = CAST(([117mobulletcurve] * 100) AS varchar),
        [118M]    = CAST(([118mobulletcurve] * 100) AS varchar),
        [119M]    = CAST(([119mobulletcurve] * 100) AS varchar),
        [120M]    = CAST(([120mobulletcurve] * 100) AS varchar),
        [121M]    = CAST(([121mobulletcurve] * 100) AS varchar),
        [122M]    = CAST(([122mobulletcurve] * 100) AS varchar),
        [123M]    = CAST(([123mobulletcurve] * 100) AS varchar),
        [124M]    = CAST(([124mobulletcurve] * 100) AS varchar),
        [125M]    = CAST(([125mobulletcurve] * 100) AS varchar),
        [126M]    = CAST(([126mobulletcurve] * 100) AS varchar),
        [127M]    = CAST(([127mobulletcurve] * 100) AS varchar),
        [128M]    = CAST(([128mobulletcurve] * 100) AS varchar),
        [129M]    = CAST(([129mobulletcurve] * 100) AS varchar),
        [130M]    = CAST(([130mobulletcurve] * 100) AS varchar),
        [131M]    = CAST(([131mobulletcurve] * 100) AS varchar),
        [132M]    = CAST(([132mobulletcurve] * 100) AS varchar),
        [133M]    = CAST(([133mobulletcurve] * 100) AS varchar),
        [134M]    = CAST(([134mobulletcurve] * 100) AS varchar),
        [135M]    = CAST(([135mobulletcurve] * 100) AS varchar),
        [136M]    = CAST(([136mobulletcurve] * 100) AS varchar),
        [137M]    = CAST(([137mobulletcurve] * 100) AS varchar),
        [138M]    = CAST(([138mobulletcurve] * 100) AS varchar),
        [139M]    = CAST(([139mobulletcurve] * 100) AS varchar),
        [140M]    = CAST(([140mobulletcurve] * 100) AS varchar),
        [141M]    = CAST(([141mobulletcurve] * 100) AS varchar),
        [142M]    = CAST(([142mobulletcurve] * 100) AS varchar),
        [143M]    = CAST(([143mobulletcurve] * 100) AS varchar),
        [144M]    = CAST(([144mobulletcurve] * 100) AS varchar),
        [145M]    = CAST(([145mobulletcurve] * 100) AS varchar),
        [146M]    = CAST(([146mobulletcurve] * 100) AS varchar),
        [147M]    = CAST(([147mobulletcurve] * 100) AS varchar),
        [148M]    = CAST(([148mobulletcurve] * 100) AS varchar),
        [149M]    = CAST(([149mobulletcurve] * 100) AS varchar),
        [150M]    = CAST(([150mobulletcurve] * 100) AS varchar),
        [151M]    = CAST(([151mobulletcurve] * 100) AS varchar),
        [152M]    = CAST(([152mobulletcurve] * 100) AS varchar),
        [153M]    = CAST(([153mobulletcurve] * 100) AS varchar),
        [154M]    = CAST(([154mobulletcurve] * 100) AS varchar),
        [155M]    = CAST(([155mobulletcurve] * 100) AS varchar),
        [156M]    = CAST(([156mobulletcurve] * 100) AS varchar),
        [157M]    = CAST(([157mobulletcurve] * 100) AS varchar),
        [158M]    = CAST(([158mobulletcurve] * 100) AS varchar),
        [159M]    = CAST(([159mobulletcurve] * 100) AS varchar),
        [160M]    = CAST(([160mobulletcurve] * 100) AS varchar),
        [161M]    = CAST(([161mobulletcurve] * 100) AS varchar),
        [162M]    = CAST(([162mobulletcurve] * 100) AS varchar),
        [163M]    = CAST(([163mobulletcurve] * 100) AS varchar),
        [164M]    = CAST(([164mobulletcurve] * 100) AS varchar),
        [165M]    = CAST(([165mobulletcurve] * 100) AS varchar),
        [166M]    = CAST(([166mobulletcurve] * 100) AS varchar),
        [167M]    = CAST(([167mobulletcurve] * 100) AS varchar),
        [168M]    = CAST(([168mobulletcurve] * 100) AS varchar),
        [169M]    = CAST(([169mobulletcurve] * 100) AS varchar),
        [170M]    = CAST(([170mobulletcurve] * 100) AS varchar),
        [171M]    = CAST(([171mobulletcurve] * 100) AS varchar),
        [172M]    = CAST(([172mobulletcurve] * 100) AS varchar),
        [173M]    = CAST(([173mobulletcurve] * 100) AS varchar),
        [174M]    = CAST(([174mobulletcurve] * 100) AS varchar),
        [175M]    = CAST(([175mobulletcurve] * 100) AS varchar),
        [176M]    = CAST(([176mobulletcurve] * 100) AS varchar),
        [177M]    = CAST(([177mobulletcurve] * 100) AS varchar),
        [178M]    = CAST(([178mobulletcurve] * 100) AS varchar),
        [179M]    = CAST(([179mobulletcurve] * 100) AS varchar),
        [180M]    = CAST(([180mobulletcurve] * 100) AS varchar),
        [181M]    = CAST(([181mobulletcurve] * 100) AS varchar),
        [182M]    = CAST(([182mobulletcurve] * 100) AS varchar),
        [183M]    = CAST(([183mobulletcurve] * 100) AS varchar),
        [184M]    = CAST(([184mobulletcurve] * 100) AS varchar),
        [185M]    = CAST(([185mobulletcurve] * 100) AS varchar),
        [186M]    = CAST(([186mobulletcurve] * 100) AS varchar),
        [187M]    = CAST(([187mobulletcurve] * 100) AS varchar),
        [188M]    = CAST(([188mobulletcurve] * 100) AS varchar),
        [189M]    = CAST(([189mobulletcurve] * 100) AS varchar),
        [190M]    = CAST(([190mobulletcurve] * 100) AS varchar),
        [191M]    = CAST(([191mobulletcurve] * 100) AS varchar),
        [192M]    = CAST(([192mobulletcurve] * 100) AS varchar),
        [193M]    = CAST(([193mobulletcurve] * 100) AS varchar),
        [194M]    = CAST(([194mobulletcurve] * 100) AS varchar),
        [195M]    = CAST(([195mobulletcurve] * 100) AS varchar),
        [196M]    = CAST(([196mobulletcurve] * 100) AS varchar),
        [197M]    = CAST(([197mobulletcurve] * 100) AS varchar),
        [198M]    = CAST(([198mobulletcurve] * 100) AS varchar),
        [199M]    = CAST(([199mobulletcurve] * 100) AS varchar),
        [200M]    = CAST(([200mobulletcurve] * 100) AS varchar),
        [201M]    = CAST(([201mobulletcurve] * 100) AS varchar),
        [202M]    = CAST(([202mobulletcurve] * 100) AS varchar),
        [203M]    = CAST(([203mobulletcurve] * 100) AS varchar),
        [204M]    = CAST(([204mobulletcurve] * 100) AS varchar),
        [205M]    = CAST(([205mobulletcurve] * 100) AS varchar),
        [206M]    = CAST(([206mobulletcurve] * 100) AS varchar),
        [207M]    = CAST(([207mobulletcurve] * 100) AS varchar),
        [208M]    = CAST(([208mobulletcurve] * 100) AS varchar),
        [209M]    = CAST(([209mobulletcurve] * 100) AS varchar),
        [210M]    = CAST(([210mobulletcurve] * 100) AS varchar),
        [211M]    = CAST(([211mobulletcurve] * 100) AS varchar),
        [212M]    = CAST(([212mobulletcurve] * 100) AS varchar),
        [213M]    = CAST(([213mobulletcurve] * 100) AS varchar),
        [214M]    = CAST(([214mobulletcurve] * 100) AS varchar),
        [215M]    = CAST(([215mobulletcurve] * 100) AS varchar),
        [216M]    = CAST(([216mobulletcurve] * 100) AS varchar),
        [217M]    = CAST(([217mobulletcurve] * 100) AS varchar),
        [218M]    = CAST(([218mobulletcurve] * 100) AS varchar),
        [219M]    = CAST(([219mobulletcurve] * 100) AS varchar),
        [220M]    = CAST(([220mobulletcurve] * 100) AS varchar),
        [221M]    = CAST(([221mobulletcurve] * 100) AS varchar),
        [222M]    = CAST(([222mobulletcurve] * 100) AS varchar),
        [223M]    = CAST(([223mobulletcurve] * 100) AS varchar),
        [224M]    = CAST(([224mobulletcurve] * 100) AS varchar),
        [225M]    = CAST(([225mobulletcurve] * 100) AS varchar),
        [226M]    = CAST(([226mobulletcurve] * 100) AS varchar),
        [227M]    = CAST(([227mobulletcurve] * 100) AS varchar),
        [228M]    = CAST(([228mobulletcurve] * 100) AS varchar),
        [229M]    = CAST(([229mobulletcurve] * 100) AS varchar),
        [230M]    = CAST(([230mobulletcurve] * 100) AS varchar),
        [231M]    = CAST(([231mobulletcurve] * 100) AS varchar),
        [232M]    = CAST(([232mobulletcurve] * 100) AS varchar),
        [233M]    = CAST(([233mobulletcurve] * 100) AS varchar),
        [234M]    = CAST(([234mobulletcurve] * 100) AS varchar),
        [235M]    = CAST(([235mobulletcurve] * 100) AS varchar),
        [236M]    = CAST(([236mobulletcurve] * 100) AS varchar),
        [237M]    = CAST(([237mobulletcurve] * 100) AS varchar),
        [238M]    = CAST(([238mobulletcurve] * 100) AS varchar),
        [239M]    = CAST(([239mobulletcurve] * 100) AS varchar),
        [240M]    = CAST(([240mobulletcurve] * 100) AS varchar),
        [241M]    = CAST(([241mobulletcurve] * 100) AS varchar),
        [242M]    = CAST(([242mobulletcurve] * 100) AS varchar),
        [243M]    = CAST(([243mobulletcurve] * 100) AS varchar),
        [244M]    = CAST(([244mobulletcurve] * 100) AS varchar),
        [245M]    = CAST(([245mobulletcurve] * 100) AS varchar),
        [246M]    = CAST(([246mobulletcurve] * 100) AS varchar),
        [247M]    = CAST(([247mobulletcurve] * 100) AS varchar),
        [248M]    = CAST(([248mobulletcurve] * 100) AS varchar),
        [249M]    = CAST(([249mobulletcurve] * 100) AS varchar),
        [250M]    = CAST(([250mobulletcurve] * 100) AS varchar),
        [251M]    = CAST(([251mobulletcurve] * 100) AS varchar),
        [252M]    = CAST(([252mobulletcurve] * 100) AS varchar),
        [253M]    = CAST(([253mobulletcurve] * 100) AS varchar),
        [254M]    = CAST(([254mobulletcurve] * 100) AS varchar),
        [255M]    = CAST(([255mobulletcurve] * 100) AS varchar),
        [256M]    = CAST(([256mobulletcurve] * 100) AS varchar),
        [257M]    = CAST(([257mobulletcurve] * 100) AS varchar),
        [258M]    = CAST(([258mobulletcurve] * 100) AS varchar),
        [259M]    = CAST(([259mobulletcurve] * 100) AS varchar),
        [260M]    = CAST(([260mobulletcurve] * 100) AS varchar),
        [261M]    = CAST(([261mobulletcurve] * 100) AS varchar),
        [262M]    = CAST(([262mobulletcurve] * 100) AS varchar),
        [263M]    = CAST(([263mobulletcurve] * 100) AS varchar),
        [264M]    = CAST(([264mobulletcurve] * 100) AS varchar),
        [265M]    = CAST(([265mobulletcurve] * 100) AS varchar),
        [266M]    = CAST(([266mobulletcurve] * 100) AS varchar),
        [267M]    = CAST(([267mobulletcurve] * 100) AS varchar),
        [268M]    = CAST(([268mobulletcurve] * 100) AS varchar),
        [269M]    = CAST(([269mobulletcurve] * 100) AS varchar),
        [270M]    = CAST(([270mobulletcurve] * 100) AS varchar),
        [271M]    = CAST(([271mobulletcurve] * 100) AS varchar),
        [272M]    = CAST(([272mobulletcurve] * 100) AS varchar),
        [273M]    = CAST(([273mobulletcurve] * 100) AS varchar),
        [274M]    = CAST(([274mobulletcurve] * 100) AS varchar),
        [275M]    = CAST(([275mobulletcurve] * 100) AS varchar),
        [276M]    = CAST(([276mobulletcurve] * 100) AS varchar),
        [277M]    = CAST(([277mobulletcurve] * 100) AS varchar),
        [278M]    = CAST(([278mobulletcurve] * 100) AS varchar),
        [279M]    = CAST(([279mobulletcurve] * 100) AS varchar),
        [280M]    = CAST(([280mobulletcurve] * 100) AS varchar),
        [281M]    = CAST(([281mobulletcurve] * 100) AS varchar),
        [282M]    = CAST(([282mobulletcurve] * 100) AS varchar),
        [283M]    = CAST(([283mobulletcurve] * 100) AS varchar),
        [284M]    = CAST(([284mobulletcurve] * 100) AS varchar),
        [285M]    = CAST(([285mobulletcurve] * 100) AS varchar),
        [286M]    = CAST(([286mobulletcurve] * 100) AS varchar),
        [287M]    = CAST(([287mobulletcurve] * 100) AS varchar),
        [288M]    = CAST(([288mobulletcurve] * 100) AS varchar),
        [289M]    = CAST(([289mobulletcurve] * 100) AS varchar),
        [290M]    = CAST(([290mobulletcurve] * 100) AS varchar),
        [291M]    = CAST(([291mobulletcurve] * 100) AS varchar),
        [292M]    = CAST(([292mobulletcurve] * 100) AS varchar),
        [293M]    = CAST(([293mobulletcurve] * 100) AS varchar),
        [294M]    = CAST(([294mobulletcurve] * 100) AS varchar),
        [295M]    = CAST(([295mobulletcurve] * 100) AS varchar),
        [296M]    = CAST(([296mobulletcurve] * 100) AS varchar),
        [297M]    = CAST(([297mobulletcurve] * 100) AS varchar),
        [298M]    = CAST(([298mobulletcurve] * 100) AS varchar),
        [299M]    = CAST(([299mobulletcurve] * 100) AS varchar),
        [300M]    = CAST(([300mobulletcurve] * 100) AS varchar),
        [301M]    = CAST(([301mobulletcurve] * 100) AS varchar),
        [302M]    = CAST(([302mobulletcurve] * 100) AS varchar),
        [303M]    = CAST(([303mobulletcurve] * 100) AS varchar),
        [304M]    = CAST(([304mobulletcurve] * 100) AS varchar),
        [305M]    = CAST(([305mobulletcurve] * 100) AS varchar),
        [306M]    = CAST(([306mobulletcurve] * 100) AS varchar),
        [307M]    = CAST(([307mobulletcurve] * 100) AS varchar),
        [308M]    = CAST(([308mobulletcurve] * 100) AS varchar),
        [309M]    = CAST(([309mobulletcurve] * 100) AS varchar),
        [310M]    = CAST(([310mobulletcurve] * 100) AS varchar),
        [311M]    = CAST(([311mobulletcurve] * 100) AS varchar),
        [312M]    = CAST(([312mobulletcurve] * 100) AS varchar),
        [313M]    = CAST(([313mobulletcurve] * 100) AS varchar),
        [314M]    = CAST(([314mobulletcurve] * 100) AS varchar),
        [315M]    = CAST(([315mobulletcurve] * 100) AS varchar),
        [316M]    = CAST(([316mobulletcurve] * 100) AS varchar),
        [317M]    = CAST(([317mobulletcurve] * 100) AS varchar),
        [318M]    = CAST(([318mobulletcurve] * 100) AS varchar),
        [319M]    = CAST(([319mobulletcurve] * 100) AS varchar),
        [320M]    = CAST(([320mobulletcurve] * 100) AS varchar),
        [321M]    = CAST(([321mobulletcurve] * 100) AS varchar),
        [322M]    = CAST(([322mobulletcurve] * 100) AS varchar),
        [323M]    = CAST(([323mobulletcurve] * 100) AS varchar),
        [324M]    = CAST(([324mobulletcurve] * 100) AS varchar),
        [325M]    = CAST(([325mobulletcurve] * 100) AS varchar),
        [326M]    = CAST(([326mobulletcurve] * 100) AS varchar),
        [327M]    = CAST(([327mobulletcurve] * 100) AS varchar),
        [328M]    = CAST(([328mobulletcurve] * 100) AS varchar),
        [329M]    = CAST(([329mobulletcurve] * 100) AS varchar),
        [330M]    = CAST(([330mobulletcurve] * 100) AS varchar),
        [331M]    = CAST(([331mobulletcurve] * 100) AS varchar),
        [332M]    = CAST(([332mobulletcurve] * 100) AS varchar),
        [333M]    = CAST(([333mobulletcurve] * 100) AS varchar),
        [334M]    = CAST(([334mobulletcurve] * 100) AS varchar),
        [335M]    = CAST(([335mobulletcurve] * 100) AS varchar),
        [336M]    = CAST(([336mobulletcurve] * 100) AS varchar),
        [337M]    = CAST(([337mobulletcurve] * 100) AS varchar),
        [338M]    = CAST(([338mobulletcurve] * 100) AS varchar),
        [339M]    = CAST(([339mobulletcurve] * 100) AS varchar),
        [340M]    = CAST(([340mobulletcurve] * 100) AS varchar),
        [341M]    = CAST(([341mobulletcurve] * 100) AS varchar),
        [342M]    = CAST(([342mobulletcurve] * 100) AS varchar),
        [343M]    = CAST(([343mobulletcurve] * 100) AS varchar),
        [344M]    = CAST(([344mobulletcurve] * 100) AS varchar),
        [345M]    = CAST(([345mobulletcurve] * 100) AS varchar),
        [346M]    = CAST(([346mobulletcurve] * 100) AS varchar),
        [347M]    = CAST(([347mobulletcurve] * 100) AS varchar),
        [348M]    = CAST(([348mobulletcurve] * 100) AS varchar),
        [349M]    = CAST(([349mobulletcurve] * 100) AS varchar),
        [350M]    = CAST(([350mobulletcurve] * 100) AS varchar),
        [351M]    = CAST(([351mobulletcurve] * 100) AS varchar),
        [352M]    = CAST(([352mobulletcurve] * 100) AS varchar),
        [353M]    = CAST(([353mobulletcurve] * 100) AS varchar),
        [354M]    = CAST(([354mobulletcurve] * 100) AS varchar),
        [355M]    = CAST(([355mobulletcurve] * 100) AS varchar),
        [356M]    = CAST(([356mobulletcurve] * 100) AS varchar),
        [357M]    = CAST(([357mobulletcurve] * 100) AS varchar),
        [358M]    = CAST(([358mobulletcurve] * 100) AS varchar),
        [359M]    = CAST(([359mobulletcurve] * 100) AS varchar),
        [360M]    = CAST(([360mobulletcurve] * 100) AS varchar),
        [Fedtar]  = CAST((Fedtar * 100) AS varchar)
    FROM Pivoted
    ORDER BY CURVE, RateDate;
END

GO
